apiVersion: 1

datasources:
  - name: PostgreSQL Road Monitoring
    uid: postgres-road-monitoring
    type: postgres
    access: proxy
    url: postgres_db:5432
    user: user
    secureJsonData:
      password: pass
    jsonData:
      database: test_db
      sslmode: disable
      postgresVersion: 1600
      timescaledb: false
    isDefault: true
    editable: false
